import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
import { chromium } from 'playwright';
const PAGE='fungi_solution.html', OUT=process.argv[2];
const ROOT=path.resolve('C:/EPA/US/website_project/_deploy');
const MIME={'.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png','.jpg':'image/jpeg','.mp4':'video/mp4'};
const srv=http.createServer((q,r)=>{let u=decodeURIComponent(q.url.split('?')[0]); if(u==='/')u='/'+PAGE; const fp=path.join(ROOT,u); if(!fp.startsWith(ROOT)||!fs.existsSync(fp)||fs.statSync(fp).isDirectory()){r.statusCode=404;return r.end('nf');} r.setHeader('Content-Type',MIME[path.extname(fp)]||'application/octet-stream'); fs.createReadStream(fp).pipe(r);});
await new Promise(res=>srv.listen(0,res)); const port=srv.address().port;
const b=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const p=await b.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
await p.goto(`http://localhost:${port}/${PAGE}`,{waitUntil:'domcontentloaded',timeout:45000}).catch(()=>{});
await p.evaluate(()=>{ window.__b=0; window.__m=0; window.__max=0;
  const anno=document.querySelector('.anno');
  const mo=new MutationObserver(muts=>{ for(const mu of muts){ if(mu.type==='attributes'&&mu.target.classList&&mu.target.classList.contains('spore')){ if(mu.target.classList.contains('captured')) window.__b++; else if(mu.target.classList.contains('settled')) window.__m++; } } });
  mo.observe(anno,{subtree:true,attributes:true,attributeFilter:['class']});
  setInterval(()=>{ const n=anno.querySelectorAll('.spore').length; if(n>window.__max) window.__max=n; },50);
});
await p.waitForTimeout(3000);
await p.$('#videoStack').then(e=>e.screenshot({path:OUT}));
await p.waitForTimeout(4000);
const r=await p.evaluate(()=>({blue:window.__b,mold:window.__m,maxConcurrent:window.__max,spores:document.querySelectorAll('.spore').length,ended:document.querySelector('video').ended}));
console.log('landed blue(NanoFlashing)='+r.blue+'  mold(conventional)='+r.mold+'  maxConcurrent='+r.maxConcurrent+'  now='+r.spores+' ended='+r.ended);
await b.close(); srv.close();
