import { chromium } from 'playwright';
const URL=process.argv[2], OUT=process.argv[3], W=parseInt(process.argv[4]||'1863',10);
const b=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const p=await b.newPage({viewport:{width:W,height:1007},deviceScaleFactor:1});
const errs=[]; p.on('pageerror',e=>errs.push(String(e)));
await p.goto(URL,{waitUntil:'networkidle',timeout:60000}).catch(()=>{});
await p.waitForTimeout(3000);
const d=await p.evaluate(()=>{const s=document.getElementById('videoStack'); const sb=s.getBoundingClientRect(); const c=(q)=>{const e=document.querySelector(q); if(!e)return null; const r=e.getBoundingClientRect(); return +(((r.left+r.right)/2 - sb.left)/sb.width*100).toFixed(1);}; return {nf:c('.anno-lbl-nf'),cv:c('.anno-lbl-cv'),top:c('.anno-top'),spores:document.querySelectorAll('.anno .spore').length};});
await p.screenshot({path:OUT});
console.log('LIVE@'+W+' nf='+d.nf+'% cv='+d.cv+'% top='+d.top+'% spores='+d.spores+' errs='+errs.length);
await b.close();
