import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
import { chromium } from 'playwright';
const PAGE=process.argv[2], OUT=process.argv[3], WAIT=parseInt(process.argv[4]||'2600',10);
const ROOT=path.resolve('C:/EPA/US/website_project/_deploy');
const MIME={'.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png','.jpg':'image/jpeg','.mp4':'video/mp4'};
const srv=http.createServer((q,r)=>{let u=decodeURIComponent(q.url.split('?')[0]); if(u==='/')u='/'+PAGE; const fp=path.join(ROOT,u); if(!fp.startsWith(ROOT)||!fs.existsSync(fp)||fs.statSync(fp).isDirectory()){r.statusCode=404;return r.end('nf');} r.setHeader('Content-Type',MIME[path.extname(fp)]||'application/octet-stream'); fs.createReadStream(fp).pipe(r);});
await new Promise(res=>srv.listen(0,res)); const port=srv.address().port;
const b=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const p=await b.newPage({viewport:{width:1440,height:900},deviceScaleFactor:2});
const errs=[]; p.on('pageerror',e=>errs.push(String(e)));
await p.goto(`http://localhost:${port}/${PAGE}`,{waitUntil:'domcontentloaded',timeout:45000}).catch(()=>{});
await p.waitForTimeout(WAIT);
const info=await p.evaluate(()=>({spores:document.querySelectorAll('.anno .spore').length, hasTop:!!document.querySelector('.anno-top'), vidCt:(document.querySelector('video')||{}).currentTime}));
await p.screenshot({path:OUT});
console.log('render '+PAGE+' spores='+info.spores+' hasTop='+info.hasTop+' vidCt='+(info.vidCt||0).toFixed(2)+' errs='+errs.length+(errs.length?' :: '+errs[0].slice(0,160):''));
await b.close(); srv.close();
