import { chromium } from 'playwright';
const URL=process.argv[2], OUT=process.argv[3], WAIT=parseInt(process.argv[4]||'3600',10);
const b=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const p=await b.newPage({viewport:{width:1440,height:900},deviceScaleFactor:2});
const errs=[]; p.on('pageerror',e=>errs.push(String(e)));
await p.goto(URL,{waitUntil:'networkidle',timeout:60000}).catch(()=>{});
await p.waitForTimeout(WAIT);
const info=await p.evaluate(()=>({spores:document.querySelectorAll('.anno .spore').length,hasTop:!!document.querySelector('.anno-top'),vidCt:(document.querySelector('video')||{}).currentTime,stress:(document.querySelector('.anno-stress-x')||{}).textContent}));
await p.screenshot({path:OUT});
console.log('LIVE spores='+info.spores+' hasTop='+info.hasTop+' vidCt='+(info.vidCt||0).toFixed(2)+' stress='+info.stress+' errs='+errs.length);
await b.close();
