import { chromium } from 'playwright';
const URL=process.argv[2], OUT=process.argv[3];
const b=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const p=await b.newPage({viewport:{width:1863,height:1007},deviceScaleFactor:1});
const errs=[]; p.on('pageerror',e=>errs.push(String(e)));
await p.goto(URL,{waitUntil:'networkidle',timeout:60000}).catch(()=>{});
await p.evaluate(()=>{ window.__b=0; window.__m=0; window.__max=0; const a=document.querySelector('.anno');
  new MutationObserver(ms=>{for(const mu of ms){const t=mu.target; if(t.classList&&t.classList.contains('spore')){ if(t.classList.contains('captured'))window.__b++; else if(t.classList.contains('settled'))window.__m++; }}}).observe(a,{subtree:true,attributes:true,attributeFilter:['class']});
  setInterval(()=>{const n=a.querySelectorAll('.spore').length; if(n>window.__max)window.__max=n;},50);
});
await p.waitForTimeout(3200);
await p.$('#videoStack').then(e=>e.screenshot({path:OUT}));
await p.waitForTimeout(4500);
const r=await p.evaluate(()=>({b:window.__b,m:window.__m,max:window.__max,now:document.querySelectorAll('.spore').length,ended:document.querySelector('video').ended,loop:document.querySelector('video').loop}));
console.log('LIVE blue='+r.b+' mold='+r.m+' maxConcurrent='+r.max+' | rest spores='+r.now+' ended='+r.ended+' loop='+r.loop+' errs='+errs.length);
await b.close();
