import { chromium } from 'playwright';
const URL=process.argv[2];
const b=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const p=await b.newPage({viewport:{width:1863,height:1007},deviceScaleFactor:1});
const errs=[]; p.on('pageerror',e=>errs.push(String(e)));
await p.goto(URL,{waitUntil:'networkidle',timeout:60000}).catch(()=>{});
await p.waitForTimeout(2600);
const fall=await p.evaluate(()=>({ct:+document.querySelector('video').currentTime.toFixed(1),spores:document.querySelectorAll('.anno .spore').length}));
await p.waitForTimeout(5000);
const rest=await p.evaluate(()=>({ct:+document.querySelector('video').currentTime.toFixed(1),ended:document.querySelector('video').ended,loop:document.querySelector('video').loop,spores:document.querySelectorAll('.anno .spore').length}));
console.log('LIVE fall@'+fall.ct+'s spores='+fall.spores+' | rest@'+rest.ct+'s spores='+rest.spores+' ended='+rest.ended+' loop='+rest.loop+' errs='+errs.length);
await b.close();
